### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Riggs333**
- AssertJ
- Mockito (though not used here?)

### CODE REVIEW

**Review by jparams — APPROVED** [review]

**Comment by jparams** [comment]
Good spot that Mockito isn't used. Would you mind removing that?

**Comment by Riggs333** [comment]
Sure. I deleted the Mockito dependency.

**Comment by Riggs333** [comment]
On the recent travis builds the build failed with the message:

> The command "openssl aes-256-cbc -K $encrypted_46a4d7ddb175_key -iv $encrypted_46a4d7ddb175_iv -in key.gpg.enc -out key.gpg -d" failed and exited with 1 during .

Do you know what that is and how to fix it?

**Comment by jparams** [comment]
Should now be fixed with this PR
https://github.com/jparams/to-string-verifier/pull/12

**Pull request merged**
